version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db01
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secret

  web:
    image: nginx
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '8001:80'
      - '8002:443'
    depends_on:
      - php-fpm

  php-fpm:
    image: php:7.3.1-fpm
    volumes:
      - ../src:/var/www
